# Generated by Django 6.0 on 2025-12-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('duracion_meses', models.PositiveIntegerField()),
                ('horas_semanales', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicada'), ('CLOSED', 'Cerrada')], default='DRAFT', max_length=20)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('remuneracion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='companies.empresa')),
            ],
        ),
    ]
