# Generated by Django 6.0 on 2025-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_state',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('CONDICIONAL', 'Condicional'), ('LIBRE', 'Libre'), ('GRADUADO', 'Graduado')], default='REGULAR', max_length=20),
        ),
    ]
