# Generated by Django 6.0 on 2025-12-18 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_academic_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('carrera', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField()),
                ('estado_academico', models.CharField(choices=[('REGULAR', 'Regular'), ('CONDICIONAL', 'Condicional'), ('LIBRE', 'Libre'), ('GRADUADO', 'Graduado')], default='REGULAR', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
