# Generated by Django 6.0 on 2025-12-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_estudiante_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='legajo',
            new_name='dni',
        ),
    ]
