# Generated by Django 6.0 on 2025-12-19 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('offers', '0001_initial'),
        ('students', '0004_rename_legajo_estudiante_dni'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVE', 'Activa'), ('SUSPENDED', 'Suspendida'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='companies.empresa')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicas', to='students.estudiante')),
                ('oferta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='offers.oferta')),
                ('tutor_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_practices', to='tutors.tutor')),
                ('tutor_empresarial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_practices', to='tutors.tutor')),
            ],
            options={
                'verbose_name': 'Práctica',
                'verbose_name_plural': 'Prácticas',
            },
        ),
    ]
