# Generated by Django 6.0 on 2025-12-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practica',
            name='tutor_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_practices', to='tutors.tutor'),
        ),
        migrations.AlterField(
            model_name='practica',
            name='tutor_empresarial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company_practices', to='tutors.tutor'),
        ),
    ]
