# Generated by Django 6.0 on 2025-12-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_alter_practica_tutor_academico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practica',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
