# Generated by Django 6.0 on 2025-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_alter_practica_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practica',
            name='estado',
            field=models.CharField(choices=[('PENDING', 'Pendiente revisión'), ('APPROVED', 'Aprobada académicamente'), ('ACTIVE', 'Activa'), ('SUSPENDED', 'Suspendida'), ('FINISHED', 'Finalizada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
    ]
