# Generated by Django 6.0 on 2025-12-19 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internships', '0001_initial'),
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ROUTINE', 'Rutinario'), ('FINAL', 'Final')], default='ROUTINE', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('documento', models.FileField(null=True, upload_to='reports/')),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='internships.practica')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tutors.tutor')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
            },
        ),
    ]
