# Generated by Django 6.0 on 2025-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
